# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecolex', '0006_auto_20160302_1942'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='documenttext',
            index_together=set([('doc_type', 'status')]),
        ),
    ]
