# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecolex', '0008_staticcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttext',
            name='status',
            field=models.CharField(choices=[('indexed', 'indexed'), ('full_index', 'full_index'), ('index_fail', 'index_fail'), ('full_index_fail', 'full_index_fail')], max_length=32),
        ),
    ]
