# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-10-30 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecolex', '0009_auto_20160620_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttext',
            name='url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
