version: "2"
services:
  web:
    image: danbaragan/ecolex_web:$EDW_BUILD_VER
    ports:
      - 8000:8000
    env_file:
      - deploy/envs/common.env
      - deploy/envs/web.env
      - deploy/envs/secret.env
    # adding environment: will override any of the above.
    # letting VAR with no '=VAL' will use value from the env docker-compose is being run
    depends_on:
      - solr
      - maria


#  web_updater:
#    image: ecolexprototype_web
#    command: bash
#    volumes_from:
#      - web
#    depends_on:
#      - web


  maria:
    image: mariadb:10.1
    env_file:
      - deploy/envs/common.env
      - deploy/envs/secret.env


  solr:
    image: danbaragan/ecolex_solr:$EDW_BUILD_VER
    ports:
      - "8983:8983"
    volumes:
      - ecolex_solr:/opt/solr/server/solr
    env_file:
      - deploy/envs/common.env
      - deploy/envs/solr.env
      - deploy/envs/secret.env



volumes:
  ecolex_solr:
    driver: local
  ecolex_db_maria:
    driver: local

