version: "2"
services:
  solr:
    image: ecolexprototype_solr
    ports:
      - "8983:8983"
    volumes:
      - ecolex_solr:/opt/solr/server/solr

  web:
    image: ecolexprototype_web
    volumes:
      - ./:/home/web/ecolex
    environment:
        - SOLR_URI=http://solr:8983/solr/ecolex
    ports:
        - 8000:8000
    depends_on:
      - solr

#  web_updater:
#    image: ecolexprototype_web
#    command: bash
#    volumes_from:
#      - web
#    depends_on:
#      - web

volumes:
  ecolex_solr:
    driver: local

